export const GET_ALL_PROYECT = "GET_ALL_PROYECT";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PROYECT_GROUP = "GET_PROYECT_GROUP";
export const SET_OFERT_STATUS = "SET_OFERT_STATUS";
export const SET_FILTER_OFERT = "SET_FILTER_OFERT";
export const SET_STATUS_OFERT = "SET_STATUS_OFERT";